name: Deploy to Railway

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Railway CLI
        run: railway --version

      - name: Deploy to Railway
        run: railway up --service=${{ env.SERVICE_ID }}
