name: Deploy FastAPI

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "✅ Add tests here later"

      - name: Build Docker image
        run: |
          docker build -t lingafriq-api .

      # Example: Deploy to Railway
      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          serviceId: ${{ secrets.RAILWAY_SERVICE_ID }}
