name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Railway CLI and Token
        run: |
          railway --version
          if [ -z "$RAILWAY_TOKEN" ]; then echo "RAILWAY_TOKEN is not set"; exit 1; fi
          echo "RAILWAY_TOKEN is set (length: ${#RAILWAY_TOKEN})"

      - name: Deploy to Railway
        run: railway up --service=${{ env.SERVICE_ID }}
